app:
    resource: '@AppBundle/Controller/'
    type: annotation

api_products_list:
    path:     /api/v1/products
    defaults: { _controller: AppBundle:Product:getAll }
    methods:  [GET]

api_categories_list:
    path:     /api/v1/categories
    defaults: { _controller: AppBundle:Category:getAll }
    methods:  [GET]

api_products_get:
    path:     /api/v1/products/{product_id}
    defaults: { _controller: AppBundle:Product:getOne }
    methods:  [GET]

api_products_create:
    path:     /api/v1/products
    defaults: { _controller: AppBundle:Product:create }
    methods:  [POST]

api_products_update:
    path:     /api/v1/products/{product_id}
    defaults: { _controller: AppBundle:Product:update }
    methods:  [POST]

api_products_delete:
    path:     /api/v1/products/{product_id}
    defaults: { _controller: AppBundle:Product:delete }
    methods:  [DELETE]
